# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - PS-204-Building-Applications-with-React-and-Redux


on:
  push:
    branches:
      - main
  workflow_dispatch:


# https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#set-up-the-environment
# 1
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@v2


    - name: Setup Node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'





# https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#build-the-web-app
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

         # working-directory: 'build'



    - name: 'Run Azure webapp deploy action using publish profile credentials'
# https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#configure-the-github-secret    
# https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#javascript
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PS-204-Building-Applications-with-React-and-Redux'
        slot-name: 'Production'
        publish-profile: ${{ secrets.secret1 }}
        package: 'build'
